from typing import Any, Dict, List, Optional, Tuple

from backend.db.Collections import CollectionObjs
from backend.db.DBConstants import DBFields, DBOperators
from backend.models_db.Rel import Rel


class RelationshipMongoMixin:
    def get_collection(self, collection):
        raise NotImplementedError

    # ========================= Family context from DB =========================

    def get_family_context_for_entity(self, entity_key: str) -> "PersonFamilyContext":
        """
        Build a PersonFamilyContext for an entity by querying the rels collection.
        Looks up childOfFather, childOfMother, spouseOf rels where this entity is term1,
        resolves term2 keys to display_en_name (lowercased).
        """
        from backend.models_db.EntityObjects.EntityIdentity import PersonFamilyContext
        from backend.models_db.Enums import RelType

        ctx = PersonFamilyContext()

        # Family rel types where this entity is term1
        family_rel_types = [
            (RelType.childOfFather, "fathers"),
            (RelType.childOfMother, "mothers"),
            (RelType.spouseOf, "spouses"),
        ]

        for rel_type, attr_name in family_rel_types:
            docs = self.get_collection(CollectionObjs.RELATIONS).find({
                DBFields.TERM1: entity_key,
                DBFields.REL_TYPE: rel_type.value,
            })
            for doc in docs:
                term2_key = doc.get(DBFields.TERM2)
                if term2_key:
                    name = self._resolve_entity_key_to_name(term2_key)
                    if name:
                        getattr(ctx, attr_name).add(name)

        # Also check spouseOf where this entity is term2 (spouse is bidirectional)
        spouse_docs = self.get_collection(CollectionObjs.RELATIONS).find({
            DBFields.TERM2: entity_key,
            DBFields.REL_TYPE: RelType.spouseOf.value,
        })
        for doc in spouse_docs:
            term1_key = doc.get(DBFields.TERM1)
            if term1_key:
                name = self._resolve_entity_key_to_name(term1_key)
                if name:
                    ctx.spouses.add(name)

        return ctx

    def _resolve_entity_key_to_name(self, entity_key: str) -> Optional[str]:
        """Resolve an entity key to its lowercased display_en_name."""
        doc = self.get_collection(CollectionObjs.ENTITIES).find_one({DBFields.KEY: entity_key})
        if doc is None:
            return None
        name = doc.get(DBFields.DISPLAY_EN_NAME, "")
        return name.lower() if name else None

    # ========================= Primary insert method =========================

    def try_insert_rel(self, rel: Rel) -> str:
        """
        Inserts a Rel if one with the same rel_type, term1 and term2 does not already exist.
        The key is auto-generated by MongoDB upon insert.
        Returns the key (str of ObjectId) whether newly inserted or already existing.
        """
        existing_key = self._find_existing_rel_key(rel)
        if existing_key:
            return existing_key

        data = rel.to_db_dict()
        data[DBFields.REL_TYPE] = rel.rel_type.value
        # Remove empty key so Mongo generates _id
        data.pop(DBFields.KEY, None)

        result = self.get_collection(CollectionObjs.RELATIONS).insert_one(data)
        generated_key = str(result.inserted_id)

        # Persist the key back into the document
        self.get_collection(CollectionObjs.RELATIONS).update_one(
            {"_id": result.inserted_id},
            {DBOperators.SET: {DBFields.KEY: generated_key}},
        )
        return generated_key

    def _find_existing_rel_key(self, rel: Rel) -> Optional[str]:
        """
        Check if a relationship with the same rel_type, term1 and term2 already exists.
        All three must match for it to be considered a duplicate.
        Returns its key if found, else None.
        """
        doc = self.get_collection(CollectionObjs.RELATIONS).find_one({
            DBFields.REL_TYPE: rel.rel_type.value,
            DBFields.TERM1: rel.term1,
            DBFields.TERM2: rel.term2,
        })
        if doc is None:
            return None
        return doc.get(DBFields.KEY) or str(doc["_id"])

    def insert_rel(self, rel: Rel) -> str:
        """
        Plain insert (no dedup check). Satisfies the RelationshipInterfaceMixin contract.
        Inserts the rel and stores the MongoDB-generated key back into the document.
        """
        data = rel.to_db_dict()
        data[DBFields.REL_TYPE] = rel.rel_type.value
        data.pop(DBFields.KEY, None)

        result = self.get_collection(CollectionObjs.RELATIONS).insert_one(data)
        generated_key = str(result.inserted_id)

        self.get_collection(CollectionObjs.RELATIONS).update_one(
            {"_id": result.inserted_id},
            {DBOperators.SET: {DBFields.KEY: generated_key}},
        )
        return generated_key

    # ========================= Query methods =========================

    def is_rel_exists(self, key: str) -> bool:
        return self.get_collection(CollectionObjs.RELATIONS).find_one({DBFields.KEY: key}) is not None

    def update_rel(self, rel: Rel) -> int:
        data = rel.to_db_dict()
        data[DBFields.REL_TYPE] = rel.rel_type.value
        key = data.pop(DBFields.KEY)
        result = self.get_collection(CollectionObjs.RELATIONS).update_one(
            {DBFields.KEY: key},
            {DBOperators.SET: data},
        )
        return result.modified_count

    def get_rel_by_key(self, key: str) -> Optional[Rel]:
        doc = self.get_collection(CollectionObjs.RELATIONS).find_one({DBFields.KEY: key})
        if doc is None:
            return None
        return self._doc_to_rel(doc)

    def get_rels_by_keys(self, keys: List[str]) -> List[Rel]:
        docs = self.get_collection(CollectionObjs.RELATIONS).find({DBFields.KEY: {DBOperators.IN: keys}})
        return [self._doc_to_rel(doc) for doc in docs]

    def get_rels_for_entity(self, entity_key: str) -> List[Rel]:
        docs = self.get_collection(CollectionObjs.RELATIONS).find(
            {
                DBOperators.OR: [
                    {DBFields.TERM1: entity_key},
                    {DBFields.TERM2: entity_key},
                ]
            }
        )
        return [self._doc_to_rel(doc) for doc in docs]

    def get_all_rels(self) -> List[Rel]:
        docs = self.get_collection(CollectionObjs.RELATIONS).find({})
        return [self._doc_to_rel(doc) for doc in docs]

    def insert_rels_bulk(self, rels: List[Rel]) -> int:
        if not rels:
            return 0
        docs = []
        for rel in rels:
            data = rel.to_db_dict()
            data[DBFields.REL_TYPE] = rel.rel_type.value
            docs.append(data)
        result = self.get_collection(CollectionObjs.RELATIONS).insert_many(docs)
        return len(result.inserted_ids)

    def upsert_rels_bulk(self, rels: List[Rel]) -> Tuple[int, int]:
        from pymongo import UpdateOne

        if not rels:
            return (0, 0)

        operations = []
        for rel in rels:
            data = rel.to_db_dict()
            data[DBFields.REL_TYPE] = rel.rel_type.value
            operations.append(UpdateOne({DBFields.KEY: rel.key}, {DBOperators.SET: data}, upsert=True))

        result = self.get_collection(CollectionObjs.RELATIONS).bulk_write(operations)
        return (result.upserted_count, result.modified_count)

    def drop_all_rels(self) -> int:
        """Delete all relationship documents from the relations collection. Returns deleted count."""
        result = self.get_collection(CollectionObjs.RELATIONS).delete_many({})
        return result.deleted_count

    def _doc_to_rel(self, doc: Dict[str, Any]) -> Rel:
        from backend.models_db.Enums import RelType

        doc = {k: v for k, v in doc.items() if k != "_id"}

        rel_type_value = doc.get(DBFields.REL_TYPE)
        doc[DBFields.REL_TYPE] = RelType(rel_type_value)

        return Rel.model_validate(doc)

